### ISSUE TITLE
Can't see overflowed actions at Samsung Galaxy S

### ISSUE THREAD

**Issue by timurgilfanov** [Cheesebaron/LegacyBar#3]
I see overflowed actions search and refresh at Galaxy Nexus (4.0.2) but cann't see it at Galaxy S (2.2.1). As I see in debug stepping in first case **ActionBarUtils.ActionFits()** called from **ActionBar.AddAction()** return false and in second case return true.

UPDATE: As I see in sources this behaviout don't contradict the logic of the project (so, it's expected behaviour), so I close this issue.

**Comment by jamesmontemagno** [comment]
Correct, you should only see action bar on API level 11+. This can be changed though in the constructor for ActionBar where we set "m_HasMenuButton"

**Comment by timurgilfanov** [comment]
Please, see [issue 5](https://github.com/Cheesebaron/MonoDroid.ActionBar/issues/5) :-)
