### ISSUE TITLE
Rename LegacyBar in base activites?

### ISSUE THREAD

**Issue by jamesmontemagno** [Cheesebaron/LegacyBar#32]
One question is should we rename this? When you have to do a findview you have to do this:

LegacyBar = FindViewById<LegacyBar.Library.Bar.LegacyBar>(Resource.Id.actionbar);

Should we rename to "CurrentLegacyBar"? Or something else?

**Comment by Cheesebaron** [comment]
Why?

**Comment by jamesmontemagno** [comment]
Oh weird git got rid of my < and > but anyways after the "findviewbyid" you have to do < with LegacyBar.Library.Bar.LegacyBar > 

and that is long... i mean idk... thoughts?

**Comment by Cheesebaron** [comment]
Use `code here` for inline code snippets ;)

Anyways, if #28 is implemented, it would not be much of an issue, but I see why you would like it to be renamed.

**Comment by jamesmontemagno** [comment]
ahhh gotcha thank you, and yeah would make sense with #28 I will close.

**Comment by jamesmontemagno** [comment]
I actually found this to be a bug that some of them aren't called legacybar though, some were still called ActionBar.

**Comment by jamesmontemagno** [comment]
Closing it out.
