### ISSUE TITLE
Application icon is not scaled in landscape mode

### ISSUE THREAD

**Issue by jorgenstorlie** [Cheesebaron/LegacyBar#40]
The bar height is ok, but the icon is not resized then rotating.

**Comment by jamesmontemagno** [comment]
Please list your device and take a screenshot. Please ensure that you have the latest code as well as this was recently updated in: https://github.com/Cheesebaron/LegacyBar/pull/37

**Comment by jorgenstorlie** [comment]
It works with latest version
